### ISSUE TITLE
Pitch step and alter not set when creating grace note

### ISSUE THREAD

**Issue by diskzero** [Webern/MusicXML-Class-Library#1]
Here is how I am configuring the NoteParams.  It works fine for rests and normal notes, but the Pitch properties are lost when creating a cue note.
`
if (item->isTemporal()) {                            
                            // Configure the note (also can be a rest)
                            const TemporalPtr temporal = std::dynamic_pointer_cast<Temporal>(item);
                            NoteParams noteParams;
                            noteParams.staffNumber = temporal->hand() + 1;
                            noteParams.voiceNumber = temporal->voice() + 1;
                            noteParams.duration = temporal->getDuration();
                            noteParams.durationType = temporal->XMLDurationType();

                            if (item->isNote()) {
                                const NotePtr note = std::dynamic_pointer_cast<Note>(item);
                                if (note->hasGrace()) {
                                    noteParams.noteChoice = NoteChoice::Choice::grace;
                                }
                                noteParams.isRest = false;
                                noteParams.isChord = note->partOfChord(tIndex, mIndex) && !note->chordMain(tIndex, mIndex);
                                noteParams.stemDirection = note->stemUp() ? mx::utility::UpDown::up : mx::utility::UpDown::down;
                                noteParams.durationDots = note->dots();
                                noteParams.showAccidental = note->accidental();
                                std::string name;
                                note->XMLPitch(name, noteParams.step, noteParams.alter, noteParams.octave);
                                // std::vector<t::BeamValue> beams;

                            } else if (item->isRest()) {
                                const RestPtr rest = std::dynamic_pointer_cast<Rest>(item);
                                noteParams.isRest = true;
                            }
                            
                            MusicDataChoicePtr noteData = createNote(noteParams);
                            partwiseMeasure->getMusicDataGroup()->addMusicDataChoice(noteData);
                        }
`

**Comment by Webern** [comment]
This should be fixed.  The functions in the mx::utility namespace are brand-new and should are not a stable interface yet.
